title: "Electromagnetismo I"
description: "Curso de Electromagnetismo I"

url: "https://mauristofeles.github.io"
baseurl: "/electro-I.github.io"


remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

markdown: kramdown

kramdown:
  input: GFM
  math_engine: mathjax

mathjax: true

collections:
  unidades:
    output: true
    permalink: /unidades/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: single
      use_math: true

  - scope:
      path: ""
      type: unidades
    values:
      layout: single
      toc: true
      use_math: true

head_scripts:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

custom_css:
  - /assets/css/custom.css

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-XK2LQN98HM"
    anonymize_ip: true

